import { AmenityItem, RoomSpec, SecurityFeature, Testimonial } from "./types";

export const BRAND_DETAILS = {
  name: "MegaMercy Apartment",
  tagline: "The Sanctuary of Modern Sovereignty",
  subtagline: "Ultra-Premium, Futuristic Short-Let Penthouse in Ikoyi, Lagos",
  location: "Bourdillon Road, Ikoyi, Lagos, Nigeria",
  shortLocation: "Ikoyi, Lagos",
  phone: "+234 814 000 7890",
  whatsapp: "+2348140007890",
  email: "concierge@megamercy.com",
  socials: {
    instagram: "https://instagram.com/megamercyapartment",
    facebook: "https://facebook.com/megamercyapartment",
    tiktok: "https://tiktok.com/@megamercyapartment",
    twitter: "https://x.com/megamercylagos",
    whatsapp: "https://wa.me/2348140007890?text=Hello%20MegaMercy%20Concierge%2C%20I%20would%20like%20to%20inquire%20about%20reserving%20the%20penthouse.",
    youtube: "https://youtube.com/@megamercyapartment",
  },
};

export const ROOMS: RoomSpec[] = [
  {
    id: "living-pavilion",
    name: "The Grand Living Pavilion",
    subtitle: "Floor-to-Ceiling Panoramic Lagos Lagoon & Ikoyi Horizon",
    description: "Designed for intimate conversations and high-stakes executive briefings. Features Italian velvet seating, custom bronze millwork, Bang & Olufsen sound architecture, and an automated glass partition leading to the private terrace.",
    dimensions: "1,200 sq.ft (111 m²)",
    capacity: "Up to 10 Guests (Entertaining)",
    bedType: "Custom Poltrona Frau Lounge Suite",
    keyFeatures: [
      "85-inch 4K Bang & Olufsen Beovision OLED",
      "Sonos multi-zone spatial audio ceiling matrix",
      "Automated Lutron sheer & blackout shades",
      "Floor-to-ceiling double-glazed acoustic windows",
      "Integrated wine showcase with sub-zero chilling",
    ],
    imageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80",
  },
  {
    id: "master-haven",
    name: "The Sovereign Master Haven",
    subtitle: "Sanctuary of Deep Rest & Private Splendor",
    description: "An acoustic cocoon engineered for world travelers recovering from long-haul flights. Includes an oversized super-king bed with organic Egyptian cotton linen, private biometric dressing sanctuary, and direct terrace access.",
    dimensions: "950 sq.ft (88 m²)",
    capacity: "2 Adults",
    bedType: "Super King Hypnos Heritage Bed",
    keyFeatures: [
      "Custom Italian Nero Marquina marble en-suite with deep soaking tub",
      "Raindance oversized rainfall shower with chromotherapy",
      "Walk-in dressing lounge with biometric safe",
      "Circadian rhythmic lighting system for jetlag recovery",
      "Private balcony overlooking Ikoyi tree canopies",
    ],
    imageUrl: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=80",
  },
  {
    id: "diplomatic-suite",
    name: "The Diplomatic Executive Suite",
    subtitle: "Acoustic Silence & High-Productivity Workstation",
    description: "Tailored for visiting dignitaries and corporate leaders. Equipped with an ergonomic Herman Miller Aeron workstation, dedicated encrypted Wi-Fi network, and an en-suite Italian travertine bathroom.",
    dimensions: "700 sq.ft (65 m²)",
    capacity: "2 Adults",
    bedType: "King Sized Plush Mattress",
    keyFeatures: [
      "Dedicated Herman Miller Aeron chair & executive leather desk",
      "Encrypted private VLAN network (1Gbps direct fiber)",
      "En-suite rainfall bathroom with heated towel racks",
      "Ultra-quiet Daikin VRV climate zone control",
      "Nespresso Vertuo coffee bar & minibar",
    ],
    imageUrl: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1600&q=80",
  },
  {
    id: "culinary-suite",
    name: "The Private Chef's Culinary Suite",
    subtitle: "Miele Precision Appliances & Calacatta Marble Island",
    description: "Whether preparing a light sunrise espresso or hosting a 5-course private tasting dinner curated by our on-demand executive chef, this culinary space matches the standards of Michelin-starred kitchens.",
    dimensions: "550 sq.ft (51 m²)",
    capacity: "Full Dining for 8",
    bedType: "N/A",
    keyFeatures: [
      "Full suite of German Miele induction, ovens, and wine coolers",
      "12-foot Calacatta gold marble breakfast & prep island",
      "Formal hand-crafted dining table seating 8 guests",
      "Reverse osmosis alkaline water filtration on tap",
      "Discreet butler pantry with secondary service entrance",
    ],
    imageUrl: "https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=1600&q=80",
  },
];

export const AMENITIES: AmenityItem[] = [
  {
    id: "power",
    title: "100% Uninterrupted Power",
    category: "Infrastructure",
    description: "Triple-redundant power infrastructure: dual industrial Stamford generators paired with an automated Tesla-style lithium solar inverter system. Zero flicker guaranteed.",
    iconName: "Zap",
    highlight: "Zero downtime guarantee",
  },
  {
    id: "security-guard",
    title: "24/7 Gated Perimeter Security",
    category: "Security",
    description: "Stationed in an elite gated close in Ikoyi with trained uniformed personnel, electronic bollards, and rapid-response armed escort standby.",
    iconName: "ShieldCheck",
    highlight: "Diplomatic protocol ready",
  },
  {
    id: "smart-locks",
    title: "Biometric & Keyless Smart Entry",
    category: "Security",
    description: "Encrypted fingerprint scanners and time-bound digital PINs. Access codes automatically expire upon checkout. Zero shared physical keys.",
    iconName: "KeyRound",
    highlight: "Military-grade encryption",
  },
  {
    id: "fiber-internet",
    title: "1Gbps Redundant Fiber Wi-Fi",
    category: "Smart Living",
    description: "High-speed dual-ISP optical fiber connection with satellite fallback and enterprise Wi-Fi 6 coverage throughout every corner of the residence.",
    iconName: "Wifi",
    highlight: "Ultra-low latency",
  },
  {
    id: "infinity-pool",
    title: "Private Horizon Infinity Pool",
    category: "Wellness",
    description: "Heated rooftop infinity pool with unobstructed vistas over the Lagos Lagoon and Victoria Island skyline. Private cabanas and sunset deck.",
    iconName: "Waves",
    highlight: "Private cabana service",
  },
  {
    id: "private-butler",
    title: "24/7 Dedicated Butler Concierge",
    category: "Hospitality",
    description: "From VIP airport tarmac clearance at Murtala Muhammed Airport to booking tables at RSVP or private yacht charters on the Lagos Lagoon.",
    iconName: "UserCheck",
    highlight: "Bespoke arrangements",
  },
  {
    id: "soundproof",
    title: "Acoustic Soundproofing",
    category: "Smart Living",
    description: "Custom triple-glazed acoustic German window assemblies ensuring utter tranquility and absolute speech privacy for confidential meetings.",
    iconName: "VolumeX",
    highlight: "Total acoustic privacy",
  },
  {
    id: "executive-fleet",
    title: "Chauffeured Armored Fleet (Add-On)",
    category: "Hospitality",
    description: "Available on-demand: Range Rover Sentinel and Mercedes-Benz S-Class with trained defensive drivers and security escort pilots.",
    iconName: "Car",
    highlight: "VIP airport protocol",
  },
];

export const SECURITY_FEATURES: SecurityFeature[] = [
  {
    id: "sec-1",
    title: "24/7 CCTV Exterior Matrix",
    category: "Physical",
    description: "High-definition thermal and optical cameras monitoring the gate, driveway, elevator vestibule, and perimeters. Zero cameras within private apartment spaces.",
    status: "24/7 Monitored",
    badge: "100% Perimeter Coverage",
  },
  {
    id: "sec-2",
    title: "Biometric Fingerprint & Dynamic PIN",
    category: "Biometric",
    description: "Commercial-grade biometric locks with cryptographic tamper alarms. Guest codes are generated uniquely and purged immediately upon departure.",
    status: "Encrypted",
    badge: "AES-256 Protected",
  },
  {
    id: "sec-3",
    title: "Gated Estate Vetting Protocol",
    category: "Physical",
    description: "All visitor vehicles and drivers are pre-cleared via our digital visitor management system prior to estate boom-gate access.",
    status: "Active",
    badge: "Pre-Screening Enforced",
  },
  {
    id: "sec-4",
    title: "Diplomatic Data Privacy (NDPR / GDPR)",
    category: "Digital & Privacy",
    description: "We do not sell, trade, or log guest itineraries publicly. Passport data for verification is encrypted at rest and permanently purged.",
    status: "Encrypted",
    badge: "Strict Confidentiality",
  },
  {
    id: "sec-5",
    title: "Dual Industrial Generators & Solar Battery",
    category: "Infrastructure",
    description: "Continuous 24/7 power guarantee with sub-millisecond automated ATS switching. Essential security and climate systems never lose power.",
    status: "Redundant",
    badge: "Zero Blackout Risk",
  },
  {
    id: "sec-6",
    title: "Fire Suppression & Smoke Sensing",
    category: "Infrastructure",
    description: "Early-warning optical smoke alarms, certified fire blankets, and automated dry-chemical suppression units inspected quarterly.",
    status: "Active",
    badge: "Safety Certified",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    guestName: "Ambassador Marcus V.",
    title: "Senior Diplomat & International Envoy",
    country: "Geneva, Switzerland",
    flag: "🇨🇭",
    rating: 5,
    date: "August 2026",
    quote: "In 22 years of foreign diplomatic service, MegaMercy stands shoulder to shoulder with the finest private residences in Zurich and London. The security protocol is unobtrusive yet airtight, and the peace in Ikoyi is absolute.",
    verifiedStay: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
  },
  {
    id: "test-2",
    guestName: "Dr. Chioma Adebayo",
    title: "Managing Partner, Global Equity Partners",
    country: "London / Lagos",
    flag: "🇬🇧",
    rating: 5,
    date: "July 2026",
    quote: "The 1Gbps dedicated fiber internet, acoustic silence, and uninterrupted power allowed our advisory board to conduct confidential M&A negotiations with zero friction. The private chef's dinner was sensational.",
    verifiedStay: true,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
  },
  {
    id: "test-3",
    guestName: "Jean-Philippe Moreau",
    title: "Chief Technology Officer, Pan-African Fintech",
    country: "Paris, France",
    flag: "🇫🇷",
    rating: 5,
    date: "June 2026",
    quote: "The 3D interactive website gave us an exact representation of the apartment, but walking inside was even more breathtaking. The sunset over the Lagos Lagoon from the private terrace is unforgettable.",
    verifiedStay: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
  },
];

export const IKOYI_LANDMARKS = [
  {
    name: "Ikoyi Club 1938",
    category: "Recreation & Golf",
    distance: "5 mins",
    description: "Prestigious members golf course, tennis courts, and private dining.",
  },
  {
    name: "RSVP & Slow Lagos",
    category: "Michelin-Grade Dining",
    distance: "7 mins",
    description: "Lagos's premier culinary destinations for contemporary dining and signature cocktails.",
  },
  {
    name: "Victoria Island Financial District",
    category: "Commerce & Banking",
    distance: "10 mins",
    description: "Corporate headquarters of multinational banks, consultancies, and tech hubs.",
  },
  {
    name: "Consulates & Diplomatic Enclaves",
    category: "Diplomatic Sector",
    distance: "8 mins",
    description: "Proximity to the British High Commission, French Embassy, and US Consulate.",
  },
  {
    name: "Lagos Yacht Club & Marina",
    category: "Waterfront Leisure",
    distance: "12 mins",
    description: "Private sailing berths and luxury boat charters departing across the lagoon.",
  },
];
